name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install pree
        run: npm i -g pree

      - name: Build docs
        run: pree build

      - name: Index docs
        run: npm run index

      - name: No Jekyll
        run: touch docs/.nojekyll
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site