name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  run:
    # this is due to an issue with ubuntu 23+
    # https://pptr.dev/troubleshooting#issues-with-apparmor-on-ubuntu
    # perhaps we should use a workaround from here if this
    # issue is going to persist in ubuntu runners:
    # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install pree
        run: npm i -g pree

      - name: Build docs
        run: pree build

      - name: Index docs
        run: npm run index

      - name: No Jekyll
        run: touch docs/.nojekyll
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site